# https://vsupalov.com/docker-arg-env-variable-guide/
ARG RUNTIME_IMAGE

FROM $RUNTIME_IMAGE AS final
WORKDIR /app
COPY . .
ARG BUILD_ID
ENV BUILD_ID=$BUILD_ID
EXPOSE 1337
ARG PROJECT_NAME
ENV RUN_PROJECT_NAME=$PROJECT_NAME
ENTRYPOINT dotnet $RUN_PROJECT_NAME.dll