version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  matrix:
  - SOLUTION_NAME: Anabasis.Api
  - SOLUTION_NAME: Anabasis.EventStore
  - SOLUTION_NAME: Anabasis.EventStore.Standalone
  - SOLUTION_NAME: Anabasis.EventStore.Snapshot.InMemory
  - SOLUTION_NAME: Anabasis.RabbitMQ
  - SOLUTION_NAME: Anabasis.Common
  - SOLUTION_NAME: Anabasis.EntityFramework
  - SOLUTION_NAME: Anabasis.Deployment
branches:
  only:
    - master
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: dotnet msbuild /restore  /p:Configuration=Release /p:version=%APPVEYOR_BUILD_VERSION% -verbosity:minimal %SOLUTION_NAME%.sln
after_test:
- cmd: appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\%SOLUTION_NAME%\bin\Release\%SOLUTION_NAME%.%APPVEYOR_BUILD_VERSION%.nupkg
test: off
test_script:
- cmd: |
   cd %APPVEYOR_BUILD_FOLDER%
   dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore
# test_script:
# - ps: |
#       if ($env:SOLUTION_NAME -eq "Anabasis.EventStore")
#       {
#         cd $env:APPVEYOR_BUILD_FOLDER ; dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore
#       }
  
  
  
# IF ($env:SOLUTION_NAME -eq "Anabasis.EventStore") {cd $env:APPVEYOR_BUILD_FOLDER ; dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore}
# test:
#   assemblies:
#     only:
#       - '**\*.Tests.dll'
#   categories:
#     except:
#       - Integration
#test_script:
#- cmd: |
#    cd %APPVEYOR_BUILD_FOLDER%
#    dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore
deploy:
  provider: NuGet
  api_key:
    secure: zuIMF/Jd5yeqbYdq9HDfTniovjEbGuRKqkBO6KrZpCiR/gjfqAgbSWhcp9htTzhb
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
