version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: dotnet msbuild /restore  /p:Configuration=Release /p:version=%APPVEYOR_BUILD_VERSION% -verbosity:minimal Anabasis.EventStore.sln
after_test:
- cmd: appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\Anabasis.EventStore\bin\Release\Anabasis.EventStore.%APPVEYOR_BUILD_VERSION%.nupkg
test: one
test_script:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore
deploy:
  provider: NuGet
  api_key:
    secure: lO5Q3lN0h5a98FiC/zqpN7yXeRjIzgWX1/74ccim/C0/Tixy6yL0jPEjWAaI5pHN
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master