version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: dotnet msbuild /restore  /p:Configuration=Release /p:version=%APPVEYOR_BUILD_VERSION% -verbosity:minimal Anabasis.EventStore.sln
after_test:
- cmd: appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%\Anabasis.EventStore\bin\Release\Anabasis.EventStore.%APPVEYOR_BUILD_VERSION%.nupkg
test: off
test_script:
- cmd: |
    cd %APPVEYOR_BUILD_FOLDER%
    dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore
# test:
#   assemblies:
#     only:
#       - '**\*.Tests.dll'
#   categories:
#     except:
#       - Integration
#test_script:
#- cmd: |
#    cd %APPVEYOR_BUILD_FOLDER%
#    dotnet test Anabasis.EventStore.Tests\Anabasis.EventStore.Tests.csproj --configuration Release --no-build --no-restore
deploy:
  provider: NuGet
  api_key:
    secure: |
     %NUGET_KEY%
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
