version: '2'

services:
  rabbitmq:
    hostname: rabbit
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_USERNAME=username
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_PLUGINS= rabbitmq_delayed_message_exchange;rabbitmq_management
      - RABBITMQ_COMMUNITY_PLUGINS= https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.9.0/rabbitmq_delayed_message_exchange-3.9.0.ez
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
volumes:
  rabbitmq_data:
    driver: local