// <auto-generated />
using Anabasis.EntityFramework.Tests.Integration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anabasis.EntityFramework.Tests.Integration.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anabasis.EntityFramework.Tests.Integration.Currency", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name", "Code");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Name = "United States dollar",
                            Code = "USD"
                        },
                        new
                        {
                            Name = "Euro",
                            Code = "EUR"
                        },
                        new
                        {
                            Name = "Japanese yen",
                            Code = "JPY"
                        },
                        new
                        {
                            Name = "Pound sterling",
                            Code = "GBP"
                        },
                        new
                        {
                            Name = "Australian dollar",
                            Code = "AUD"
                        },
                        new
                        {
                            Name = "Canadian dollar",
                            Code = "CAD"
                        },
                        new
                        {
                            Name = "Swiss franc",
                            Code = "CHF"
                        },
                        new
                        {
                            Name = "Renminbi",
                            Code = "CNY"
                        },
                        new
                        {
                            Name = "Hong Kong dollar",
                            Code = "HKD"
                        },
                        new
                        {
                            Name = "New Zealand dollar",
                            Code = "NZD"
                        },
                        new
                        {
                            Name = "Swedish krona",
                            Code = "SEK"
                        },
                        new
                        {
                            Name = "South Korean won",
                            Code = "KRW"
                        },
                        new
                        {
                            Name = "Singapore dollar",
                            Code = "SGD"
                        },
                        new
                        {
                            Name = "Norwegian krone",
                            Code = "NOK"
                        },
                        new
                        {
                            Name = "Mexican peso",
                            Code = "MXN"
                        },
                        new
                        {
                            Name = "Indian rupee",
                            Code = "INR"
                        },
                        new
                        {
                            Name = "Russian ruble",
                            Code = "RUB"
                        },
                        new
                        {
                            Name = "South African rand",
                            Code = "ZAR"
                        },
                        new
                        {
                            Name = "Turkish lira",
                            Code = "TRY"
                        },
                        new
                        {
                            Name = "Brazilian real",
                            Code = "BRL"
                        },
                        new
                        {
                            Name = "New Taiwan dollar",
                            Code = "TWD"
                        },
                        new
                        {
                            Name = "Danish krone",
                            Code = "DKK"
                        },
                        new
                        {
                            Name = "Polish złoty",
                            Code = "PLN"
                        },
                        new
                        {
                            Name = "Thai baht",
                            Code = "THB"
                        },
                        new
                        {
                            Name = "Indonesian rupiah",
                            Code = "IDR"
                        },
                        new
                        {
                            Name = "Hungarian forint",
                            Code = "HUF"
                        },
                        new
                        {
                            Name = "Czech koruna",
                            Code = "CZK"
                        },
                        new
                        {
                            Name = "Israeli new shekel",
                            Code = "ILS"
                        },
                        new
                        {
                            Name = "Chilean peso",
                            Code = "CLP"
                        },
                        new
                        {
                            Name = "Philippine peso",
                            Code = "PHP"
                        },
                        new
                        {
                            Name = "UAE dirham",
                            Code = "AED"
                        },
                        new
                        {
                            Name = "Colombian peso",
                            Code = "COP"
                        },
                        new
                        {
                            Name = "Saudi riyal",
                            Code = "SAR"
                        },
                        new
                        {
                            Name = "Malaysian ringgit",
                            Code = "MYR"
                        },
                        new
                        {
                            Name = "Romanian leu",
                            Code = "RON"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
