apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ASPNETCORE_ENVIRONMENT
        value: "{{ANABASIS_ENVIRONMENT}}"
  target:
    kind: Deployment