apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unknown-namespace
  name:  unknown-config-group-name
  labels:
    release: unknown-release
    group: unknown-group
data:
  config.group.yaml: unknown-config-group-yaml