apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: anabasis-deployment-test-app
    release: 1.0.67
    group: anabasis-test-group
  name: anabasis-deployment-test-app
  namespace: anabasis-test-group
spec:
  selector:
    matchLabels:
      app: anabasis-deployment-test-app
      release: 1.0.67
      group: anabasis-test-group
  template:
    metadata:
      labels:
        app: anabasis-deployment-test-app
        release: 1.0.67
    spec:
      containers:
      - env:
        - name: config
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: https://hub.docker.com/anabasis-deployment-test-app/NO_GIT_REPOS_DETECTED:1.0.67
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 30
        name: anabasis-deployment-test-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 1337
          name: health
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 1337
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 15
        volumeMounts:
        - mountPath: /app/config.group.yaml
          name: config-group
          subPath: config.group.yaml
        - mountPath: /app/config.app.yaml
          name: config-app
          subPath: config.app.yaml
      imagePullSecrets:
      - name: registrysecret
      volumes:
      - configMap:
          name: config-group-anabasis-test-group
        name: config-group
      - configMap:
          name: config-app-anabasis-deployment-test-app
        name: config-app