apiVersion: v1
kind: Service
metadata:
  labels:
    release: 1.0.67
  name: svc-anabasis-test-group
  namespace: anabasis-test-group
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: health
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: anabasis-deployment-test-app
    release: 1.0.67
  type: ClusterIP