apiVersion: v1
kind: Service
metadata:
  labels:
    release: 1.0.67
  name: svc-unknown-name
  namespace: unknown-namespace
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: unknown-name
    release: 1.0.67
  type: ClusterIP